### ISSUE TITLE
.table-striped .table-hover does not work

### ISSUE THREAD

**Issue by tadvi** [shakrmedia/petal#10] opened 2018-01-29 16:19 UTC
.table-striped .table-hover does not work even on the demo website.

**Comment by zvuc** [comment] 2018-02-07 02:29
Just checked it now on the demo website, and turning both options on seems to work fine as intended on both Chrome and Firefox... except Safari. Seems like Safari has some weird issues with `background-color` on `tr`, the style gets applied pretty randomly. I'll take a look into it later to see if I can find a workaround.

Thanks for reporting!

**Comment by zvuc** [comment] 2018-02-14 02:53
Fixed in 383c27c873ea0e458745c7daa6d16f13af9e7110, Released with 0.8.3

**Closed by zvuc** 2018-02-14 02:53 UTC
Labels: bug
